### ISSUE TITLE
CPU Throttled and CPU Freq extention shows critical.

### ISSUE THREAD

**Issue by anirudha-banerjee** [konkor/cpufreq#164]
Please see below my system details

Linux 4.15.0-130-generic #134-Ubuntu SMP Tue Jan 5 20:46:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Memory 23.5 GiB
Processor Intel Core i7-770 OHQ CPU@2.80GHZ 
Graphics GeForce GTX 1050/PCIe/SSE2
GNOME 3.28.2
OS type 64-bit
Disk 975.4 GB

The issue:
Whenever I shut down and restart or just restart my system, the CPU frequency extension shows critical as the default red color. The error that it shows is CPU Throttled, IRQBALANCE Detected.
This happens right after I log in to the Ubuntu desktop and the gnome desktop loads with my themes.
After powering off and restarting continuously for quite a few times, the CPU frequency shows stable. The frequency value that it shows when in critical, according to the extension, is similar to the frequency value shown when stable. 
I have checked the CPU temperature also, and that too is not any different from when it shows stable.

Please can you tell me what is the problem that is happening in the system because of which CPU frequency shows critical most of the time. If getting to know what is happening, from this information, is not possible, then please let me know how I can debug my system logs along with CPU frequency extension data so that I can find out how to fix this.

**Comment by konkor** [comment]
@anirudha-banerjee Looks like you have to make a cleaning of your cooling system when you have thermal throttle issue.

**Comment by anirudha-banerjee** [comment]
Okay. Thank you for the tip. Will try cleaning the cooling system.

**Comment by luskin72** [comment]
Hi!
It's not a matter of cooling system! I've a turbo-boosted & overclocked i7-8700K with xmp-ram and nvme system, liquid cooled and it's perfectly stable and mainly below 75 degrees.

Anyway, at boot (I'm running Debian 10 with Gnome), boot it's so fast that sometimes cpu throttles 1-4 times.

So, I've to see the red-critical frequency for weeks (rarely I reboot my machine) just for those initial throttlings??

It's not possible to implement a way to reset that counting or simply to (auto)reset red-critical indication?
It would be cool to have a timed alarm autoreset or even a manual reset button: ok, I've understood cpu has throttled 3 times but then for me it's ok... leave me work in peace :-)

Also because, for example, if now I'll going to convert a 4k video with handbrake and really pump up the cpu, I won't see any change in alrm indication (it was red and it will remain red... so... what's useful for??)

Any effort in this direction will be appreciated! :-)

**Comment by konkor** [comment]
@luskin72 Actually, it is a bug. There was a timer for that resetting after 15 minutes of stable work or after opening the app...

I will try to fix it in the next release.

Thank you for reporting.
