### ISSUE TITLE
Support for GNOME Shell 40

### ISSUE THREAD

**Issue by tenfourty** [konkor/cpufreq#168]
I'm on Fedora 34 beta with Gnome Shell 40 and this extension has stopped working.

**Comment by TheConner** [comment]
I was about to make a new issue but saw this one instead, figured I'd resurrect it, maybe. I recently updated to Gnome 40 (opensuse tumbleweed), and I noticed this extension is marked as "incompatible" with gnome 40
![image](https://user-images.githubusercontent.com/59540839/115115329-ed7d7b80-9f61-11eb-8808-0ee365c8c4c4.png)

I noticed you added gnome 40 to the extensions [metadata](https://github.com/konkor/cpufreq/blob/526b792aeafbb5115f47a6f47084c19c3e7a36fb/metadata.json.in#L6), but I don't think a release has been pushed with this update. Are there any major code changes you need to make in order to support gnome 40?

Thanks :smile:

**Comment by TheConner** [comment]
Following up - I was able to get this working on gnome 40 by adding `"40"` to the shell-versions in `metadata.json`, and then following the manual build and install steps

**Comment by konkor** [comment]
@TheConner The thing is the extension’s installations stopped working on many older GNOME Shell versions bcs of that changing of the new versioning system. Looks like they are expecting 3 as major version and when they see 40 it terminates installation process. I don't know what to do with this. Should I drop supporting for all older Shells or just newer one?
