### ISSUE TITLE
Weird interface on Fedora 23 (Gnome shell 3.18)

### ISSUE THREAD

**Issue by Kriptonium** [konkor/cpufreq#4]
Hi, there!  Great project you have. With this extension, suppose I can get benefit to tune my CPU into powersave mood or performance mood.. but unlucky, I cant get this cpufreq work well on my fedora 23. Could you have a look?

I am using gnome shell 3.18 ,  kernel 4.5.5-201.fc23.x86_64 and package kernel-tools-4.5.5-201.fc23.x86_64 is already installed.

I get this interface  when installing to my desktop
![selection_007](https://cloud.githubusercontent.com/assets/10372254/15806356/19760138-2b74-11e6-8e1a-6fe3bb486ff4.png)

I already chmod the cpufreqctl inside extension folder
```
$ ls -l | grep cpufreqctl
-rwxr-xr-x. 1 krip krip  557 May  7 00:55 cpufreqctl
```

**Comment by konkor** [comment]
This is already fixed in the latest version for newest kernels.
https://github.com/konkor/cpufreq/archive/master.zip
The new extension is pending for review on _extensions.gnome.org_. You can install the latest extension from github or just wait for review in 10-14 days.
u can do it manualy or through the gnome-tweaker-tool (1st remove old version in tweaker or nautilus)
Best Regards.
