### ISSUE TITLE
Add an option for polling refresh time

### ISSUE THREAD

**Issue by sandeepb1** [konkor/cpufreq#40]
The extension is great but I always have a feeling if an extension is polling the CPU statistics every second that it's actually putting load on the CPU just to get that information.

Is it possible to add an option in preferences to change the refresh time

**Comment by RicardoEPRodrigues** [comment]
@konkor has made sure to use a very optimized code base. I do understand your point, yet the way it was implemented it is very power efficient.

An option could be added, but it wouldn't really have an impact. (I my opinion, I may always be wrong)

**Comment by konkor** [comment]
**Don't worry about it.** The older version of the CPU polling methods was slow and used bash daemon for it. Later I made async reading because it was slow on some `weak` HDD. But now the extension is using direct memory kernel streams to it. The current method is faster in **thousands times** than classic old methods...

**Comment by konkor** [comment]
@sandeepb1 So the polling of the CPU loading works only when extensions opened/visible...

**Comment by sandeepb1** [comment]
OK, this sounds like a non-issue then. I think as a feature enhancement to add it in as a preference item but I understand your point that it won't bog down resources.

**Comment by konkor** [comment]
@sandeepb1 Thank you for your report. I'm closing this issue because it can freely monitor each 1ms and now it monitors each 1000ms only.
