### ISSUE TITLE
[Feature Proposal] CLI interface

### ISSUE THREAD

**Issue by pxcask** [konkor/cpufreq#80]
I like it very much!
Is it possible to implement command line usage to start own presets from a skript?

[edited: split into two feature requests]

**Comment by konkor** [comment]
@pxcask Thanks for your warm respond! Also I'm really appreciate it when users ask for some features. It helps to point the development in a right direction.

BTW Can you separate your proposals in two different issues? It could help to discuss about it and tracking it more convenient. Thanks.

_About the first one:_ Now, the application has 3 basic components: cpufreq-service daemon for monitoring, cpufreqctl helper for ROOT operations basically, and the Gnome extension for indicators and all main logic including profiles. I have plans to move all main logic to separate Gtk application to free up system resources. It's not just to make something different UI it's about enhancement and growing the solution. So that has other benefits like compatibility with other desktop environments and couldn't affect Gnome shell's resources.

Actually to do that CLI interface for profiles we have several options:
1. We can move it to cpufreqctl helper. Logically, it's the best idea because it sets up all CPU cores anyway but it's just BASH script now. It's like we have to implement loading, parsing JSON and applying profiles settings in it. So profiles are not small and simple, they could have absolutely different  options for each core thread. That sounds like it's good idea to migrate it to glib too.
2. We can move it to cpufreq-service and install it system-widely itself. But I'm not sure about it. It have to monitor all system parameters in very short time intervals and should not overload a system.
3. We could implement that CLI in the future Gtk application so.

_Maybe I'm overthinking all of it but some even small changes could affect users and I have to spend weeks on bug trackers, IRC, emails, forums etc to find solutions to all users._


-------
Please consider to support the author's desktop projects and [make donation](https://github.com/konkor/cpufreq#donations) Thank you!

**Comment by konkor** [comment]
Actually, it's partially done in the new gtk port. Try

```sh
./cpufreq-application --profile=battery|balanced|performance|user|default

## See all options on
./cpufreq-application --help

## also could be useful here --no-save option for temporary profiles for an example:
./cpufreq-application --profile=performance --no-save

##  --profile option is disabling GUI so after applying some profile it will exit like normal CLI tool
```

BTW: I'm planning to make pure CLI daemon too. I'm going to replace all Shell Script calls wit it.

**Comment by konkor** [comment]
I think The issue can be closed. **cpufreq-application** has CLI interface. Also **cpufreqctl** command has all possible CLI used by the application itself for all sort of tasks ([all options for cpufreqctl command](https://github.com/konkor/cpufreq/blob/8269ed9e1124b8c5e643342938cc307cb088338f/cpufreqctl#L38)).
