### ISSUE TITLE
nothing appens when i click top bar gnome 3.32

### ISSUE THREAD

**Issue by blazessdd** [konkor/cpufreq#95]
i don't know how to probidde more info
edit: also the freq is always shown as critical

**Comment by konkor** [comment]
Try to run the main application from terminal:

```sh
cd ~/.local/share/gnome-shell/extensions/cpufreq@konkor
./cpufreq-application
```

**Comment by konkor** [comment]
Did you find your issue? So you see red frequency indicator? It means your system overloaded by some processes. You should take a look at `sudo top' too.

**Comment by blazessdd** [comment]
system isnt overloaded but the app is telling me so 
can i post a picture?
running from terminal only shows this warning:
`
[andrea@archlinux ~]$ cd ~/.local/share/gnome-shell/extensions/cpufreq@konkor
[andrea@archlinux cpufreq@konkor]$ ./cpufreq-application
set guid: balanced balanced

(cpufreq-application:10428): Gtk-WARNING **: 17:41:14.018: gtk_window_present_with_time() should not be called with 0, or GDK_CURRENT_TIME as a timestamp, the timestamp should instead be gathered at the time the user initiated the request for the window to be shown
set turbo
`

**Comment by konkor** [comment]
Ofc you can drop pictures here.

Are you using Wayland? I didn't really tested the app on it...

**Comment by blazessdd** [comment]
im using x11 sometimes the app opens but  i cant tell why neither journalctl -f or running from terminal give a clue.
battery and user files are generated in home at log in

**Comment by konkor** [comment]
@blazessdd Oh, now I see some issues:
1. That System Loading info label doesn't work well. I'll replace it with just % for now.
2. You mentioned `battery` profile and I see battery icon so. Looks like your system really overloaded because of auto-generated `Battery` power profile. It's too aggressive now (50% cores, max frequency 50% and turbo:OFF) and it doesn't work well for your system. I have to fix it. But for now open preferences, go to 'Power Events' tab and set _do nothing_ in profile selector. You can create own power profile for battery less aggressive and select there. You can call preferences:

```sh
./cpufreq-preferences

## or use any other system tool like
gnome-shell-extension-prefs
```

After that you should select suitable current profile for you or restart.

```sh
./cpufreq-application --profile=balanced
## OR to reset to default system profile
./cpufreq-application --profile=system
## see all options
./cpufreq-application --help
```

**Comment by blazessdd** [comment]
![Screenshot from 2019-03-20 11-14-42](https://user-images.githubusercontent.com/45053339/54676659-6a2e9900-4b01-11e9-97f0-33f2da858638.png)

is this a correct behavoir? i don't remember this files being generated before were they hidden?
dashboard icon too seems corrupted

**Comment by konkor** [comment]
@blazessdd OMG You are the best tester. I see other couple issues _intel_pstate_ related. I didn't test it yet. I will try to test it today.

BTW My app didn't generate any file profiles. It means you are using other tools for power management like (TLP, laptop-mode or other). I think it was the cause of the overloading (several tools tried to manage CPU state constantly).  What's inside of files them?

**Comment by blazessdd** [comment]
[battery.txt](https://github.com/konkor/cpufreq/files/2988710/battery.txt)
machine code (added txt because i cant upload it otherwise) they don't appear if i disable cpufreq
so i cant use tlp and cpufreq together? or  there is something to do?

**Comment by konkor** [comment]
@blazessdd Actually, you can use the extension for monitoring. Just you have to decide what application should handle cpu settings on battery or other events. You could disable cpu handle in TLP config by commenting single string. Or just disable that event in the cpufreq prefs as you already did.

So these files are looking like memory dumps on crash.

**Comment by blazessdd** [comment]
ok now  with this settings the extension works i just have to remember not to touch the last line and leave it on default to use it with TLP XD 
i've never experienced the problem with the gnome-exension version because of different default settngs
can you make the default settings battery do nothing and default(--profile=system) beacause once activate it hangs whole gnome and sometimes restarts the shell if you try to change settings trough the applet

another question:the system load indicator where actually stops? its always above 50% (idle) an can reach way past 500%(honestly i didn't get what actually measures)

**Comment by konkor** [comment]
@blazessdd It's okay that you re going to manage power events with TLP at least now and on GNOME 32 :) But you could miss the ability to easy change your CPU settings and quick selecting custom user profiles. Whole thing about this extension was to make it possible and clear. Otherwise anyone could just make BASH scripts to analogy of profiles and run them as ROOT from terminal or just use TLP or laptop-mode-tools or any other solutions.

I've moved almost all code from GNOME Shell main thread to separate processes for monitoring, main manager GUI, preferences to free the resources of GNOME up and to have space to grow. I have plans to replace of functionality of TLP and other tools for monitoring and power/performance management like temperature monitors, display brightness, video cards profiles, HDD power saving features, IO scheduling for PCI, USB devices, user actions on events and more. The extension was not planned for. It was just simple governor changer... So to make that possible i'm changing all architecture and moving to other complex multi-project solution. One thing about It's not easy to do because all those features including current CPU features is impossible to test, debug for all kinds of hardware and distros in virtual environment. So it's not so easy how it's looks.

Now _System Loading_ is parameter shows actually the number of active full tasks processing by Linux kernel. So 50% is analogy to system monitor for 8 CPU cores will be 50% / 8 = 6.25%, 500% / 8 = 62.5%... If that value goes upper then 100% system monitors making that value as maximum 100% and you couldn't understand 100% is exactly enough to your tasks or you just need to add extra CPU cores or up Max Frequency or choose more efficient governor or IO scheduler.

**Comment by zer09** [comment]
Same here, it will open but will take to long, now my cpu is just running on 400MHz, it become so slow even just trying to switch app ```alt+tab``` will take a second. It also create a file named ```user``` in my home directory.

**Comment by zer09** [comment]
Same here, it will open but will take to long, now my cpu is just running on 400MHz, it become so slow even just trying to switch app ```alt+tab``` will take a second. It also create a file named ```user``` in my home directory.
This just happen a few minutes ago when a update the cpufreq. I already did power cycle my machine.

![Screenshot from 2019-03-21 20-12-57](https://user-images.githubusercontent.com/780780/54751915-52e1cf80-4c17-11e9-9ce3-86862113e243.png)

**Comment by konkor** [comment]
@zer09 Did you removed battery profile in the settings? Try this: https://github.com/konkor/cpufreq/issues/95#issuecomment-474763425

**Comment by zer09** [comment]
Nope

**Comment by konkor** [comment]
OMG this base frequency 400 MHz It's like back to 90's.

**Comment by zer09** [comment]
For now I just revert to old version, because my laptop becomes unusable.

**Comment by blazessdd** [comment]
now works like a charm, you can close this thanks ;)

**Comment by laichiaheng** [comment]
It still happens on Manjaro.
